name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Load environment
      uses: GuillaumeFalourd/convert-json-to-env@v1
      with:
        json_file: ./config/module.config.json

    - name: Build Pad
      run: |
        npm install
        npm run build:pad

    - name: Upload Pad Release Zip
      uses: actions/upload-artifact@v4
      with:
        name: pad-${{ env.VERSION }}
        path: "dist/**"
        overwrite: true

    - name: Build Fold
      run: |
        npm run build:fold

    - name: Upload Fold Release Zip
      uses: actions/upload-artifact@v4
      with:
        name: fold-${{ env.VERSION }}
        path: "dist/**"
        overwrite: true

    - name: Build Ext Pad
      run: |
        npm run build-ext:pad

    - name: Upload Ext Pad Release Zip
      uses: actions/upload-artifact@v4
      with:
        name: pad-ext-${{ env.VERSION }}
        path: "dist/**"
        overwrite: true

    - name: Build Ext Fold
      run: |
        npm run build-ext:fold

    - name: Upload Ext fold Release Zip
      uses: actions/upload-artifact@v4
      with:
        name: fold-ext-${{ env.VERSION }}
        path: "dist/**"
        overwrite: true
        
    - name: Build Transplant Pad
      run: |
          npm run build:transplant
  
    - name: Upload Transplant Pad Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: transplant-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true

    - name: Build Ext Transplant Pad
      run: |
          npm run build-ext:transplant
  
    - name: Upload Transplant Pad Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: transplant-ext-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true
  
