name: NodeJs with Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Load environment
      uses: GuillaumeFalourd/convert-json-to-env@v1
      with:
        json_file: ./config/module.config.json

    - name: Build Pad
      run: |
        npm install
        npm run build:pad

    - name: Upload Pad Release Zip
      uses: actions/upload-artifact@v4
      with:
        name: pad-${{ env.VERSION }}
        path: "dist/**"
        overwrite: true

    - name: Build Fold
      run: |
        npm run build:fold

    - name: Upload Fold Release Zip
      uses: actions/upload-artifact@v4
      with:
        name: fold-${{ env.VERSION }}
        path: "dist/**"
        overwrite: true

    - name: Build Ext Pad
      run: |
        npm run build-ext:pad

    - name: Upload Ext Pad Release Zip
      uses: actions/upload-artifact@v4
      with:
        name: pad-ext-${{ env.VERSION }}
        path: "dist/**"
        overwrite: true
        
    - name: Build Pad Compatibility Use YudiForHyperOS
      run: |
          npm run build:pad-compatibility=yudi-for-hyperos
  
    - name: Upload Pad Compatibility Use YudiForHyperOS Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: pad-yudi-for-hyperos-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true

    - name: Build Pad Compatibility Use ShengForHyperOS
      run: |
          npm run build:pad-compatibility=sheng-for-hyperos
  
    - name: Upload Pad Compatibility Use ShengForHyperOS Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: pad-sheng-for-hyperos-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true

    - name: Build Pad Mode Use MagicWindow
      run: |
          npm run build:pad-mode=magicWindow
  
    - name: Upload Pad Mode Use MagicWindow Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: pad-magicWindow-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true
  
    - name: Build Pad Compatibility Use padTiramisu
      run: |
          npm run build:pad-compatibility=general-tiramisu
  
    - name: Upload Pad Compatibility Use padTiramisu Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: general-tiramisu-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true

    - name: Build Pad Compatibility Use HyperOSBasedOnTiramisu
      run: |
          npm run build:pad-compatibility=hyperos-based-on-tiramisu
  
    - name: Upload Pad Compatibility Use HyperOSBasedOnTiramisu Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: pad-hyperos-based-on-tiramisu-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true

    - name: Build Pad Compatibility Use PipaForPad
      run: |
          npm run build:pad-compatibility=pipa-for-pad
  
    - name: Upload Pad Compatibility Use PipaForHyperOS Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: pad-pipa-for-pad-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true

    - name: Build Pad Compatibility Use LiuqinForPad
      run: |
          npm run build:pad-compatibility=liuqin-for-pad
  
    - name: Upload Pad Compatibility Use LiuqinForPad Release Zip
      uses: actions/upload-artifact@v4
      with:
          name: pad-liuqin-for-pad-${{ env.VERSION }}
          path: "dist/**"
          overwrite: true