name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Load environment
      uses: GuillaumeFalourd/convert-json-to-env@v1
      with:
        json_file: ./module_src/module.config.json
    - run: echo ${{ env.VERSION }}

    - name: Build
      run: |
        npm install
        gulp publish

    - name: Upload Release Zip
      uses: actions/upload-artifact@v4
      with:
        name: release/${{ env.VERSION }}
        path: "release/*.zip"
        compression-level: 0
